I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 14, in script
    image flayon_neutral=im.scale('images/flayon/flayon_neutral.png', 300,300)
  File "game/script.rpy", line 14, in <module>
    image flayon_neutral=im.scale('images/flayon/flayon_neutral.png', 300,300)
AttributeError: module 'renpy.display.im' has no attribute 'scale'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 14, in script
    image flayon_neutral=im.scale('images/flayon/flayon_neutral.png', 300,300)
  File "C:\Users\vikr4\OneDrive\Desktop\palulu\renpy-8.2.1-sdk\renpy\ast.py", line 922, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\vikr4\OneDrive\Desktop\palulu\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 14, in <module>
    image flayon_neutral=im.scale('images/flayon/flayon_neutral.png', 300,300)
AttributeError: module 'renpy.display.im' has no attribute 'scale'

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
ProjectFlayear 1.0
Sat Jul 13 14:38:59 2024
